language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script: true
  - nosetests --with-coverage --coverage report

script:
  - python TestCalculator.py

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: software-engineering-lab
  on:
    repo: jasperlin1996/Software-Engineering-Lab
